#!/usr/bin/env python3
"""Generate the id-side copies of things derived from idc.py's RUNTIME.

From the same source of truth:

  back/tgt/c/runtime/runtime.id  emit_runtime(), the prelude verbatim
  back/tgt/c/runtime/extern.gen.id  the same prelude, external linkage
  compiler/parse/conf.id's resv_names_src  the helper names the prelude
    defines, one space-separated constant, which an id program may
    therefore not name a function after (split into resv_names at
    startup by mid/form/unique/scan/more/reserved/reserved.id's
    init_resv_names)

The id-written compiler must emit the exact same C as idc.py, including the
runtime prelude. Rather than hand-copy that ~90-line block (and risk drift),
this regenerates an id function `emit_runtime()` that prints it verbatim.

id string literals are passed through to C unchanged, so escaping the runtime
for an id string literal is exactly C-string escaping. Run after changing
idc.py's RUNTIME:  python3 tools/gen_runtime_id.py
"""
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, ROOT)
import idc  # noqa: E402

OUT = os.path.join(ROOT, "compiler", "parse",
                   "back", "tgt", "c", "runtime", "runtime.id")
CRT_OUT = os.path.join(ROOT, "compiler", "parse",
                       "back", "tgt", "c", "runtime", "extern.gen.id")
# resv_names_src lives in the parser project's own conf.id (a hand-maintained
# file) rather than in a generated .id of its own, one space-separated string
# constant the same way builtin_src already is: NOT a list constant, even
# though list constants are allowed now (docs/PROJECT.md 5) -- compiler/parse
# is what bin/idc bootstraps stage 1 from (bootstrap/idparse.c), and stage 0
# cannot emit correct C for a list constant it predates, so the compiler's own
# bootstrap-critical source cannot be the first place that construct is used.
# write_reserved replaces only the marked block below, leaving the rest of the
# file alone. mid/names/exports/extern/builtin/more/names.id splits it, the
# way it already splits builtin_src into bnames.
RESV_CONF = os.path.join(ROOT, "compiler", "parse", "conf.id")
RESV_BEGIN = "// --- BEGIN GENERATED: tools/gen_runtime_id.py (resv_names_src) ---\n"
RESV_END = "// --- END GENERATED ---\n"


def escape(s: str) -> str:
    return s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def main():
    # idc.py joins RUNTIME with the rest using "\n"; RUNTIME already ends with a
    # newline, so the printed block must end at the final "}" (the caller adds
    # the blank line). Drop exactly one trailing newline.
    runtime = idc.RUNTIME
    if runtime.endswith("\n"):
        runtime = runtime[:-1]

    body = escape(runtime)
    with open(OUT, "w") as f:
        f.write(
            "// GENERATED by tools/gen_runtime_id.py from idc.py's RUNTIME -- do\n"
            "// not edit. Prints the C runtime prelude verbatim so the id-written\n"
            "// compiler emits byte-identical C to idc.py.\n"
            "\n"
            "emit_runtime() {\n"
            f'  print("{body}");\n'
            "} return void;\n"
        )
    print(f"wrote {OUT} ({len(runtime)} bytes of runtime)")
    write_extern(runtime)
    write_reserved()


def write_extern(runtime):
    """The same prelude with external linkage, for the LLVM target.

    The C target splices the runtime into one translation unit and marks every
    helper `static`; the LLVM target compiles it as a translation unit of its
    own that a separate .ll calls into, so the same helpers have to be visible.
    Generated rather than stripped at run time because `id` builds a string by
    concatenation, and rewriting sixteen kilobytes that way is quadratic.

    This file exists only while the LLVM target links a C runtime. The runtime
    written in `id` replaces it -- see docs/LLVM.md.
    """
    body = escape(runtime.replace("\nstatic ", "\n"))
    with open(CRT_OUT, "w") as f:
        f.write(
            "// GENERATED by tools/gen_runtime_id.py from idc.py's RUNTIME -- do\n"
            "// not edit. The C runtime with external linkage, which is what the\n"
            "// LLVM target links against: it compiles the runtime as its own\n"
            "// translation unit rather than splicing it into the program.\n"
            "\n"
            "emit_crt() {\n"
            f'  print("{body}");\n'
            "} return void;\n"
        )
    print(f"wrote {CRT_OUT} (external-linkage runtime)")


def write_reserved():
    """The runtime helper names, as one space-separated conf.id string.

    Derived from idc.py's RUNTIME_HELPERS, which is itself derived from
    RUNTIME, so adding a helper to the prelude reserves its name in both
    compilers in the same commit. tests/stdlib.sh asserts the two agree.
    Every id function is emitted as id_<name>, so an id function named after
    one of these collides with the runtime in C; is_reserved_name
    (mid/form/unique/scan/more/reserved/check.id) is what catches it, over
    resv_names, which mid/names/exports/extern/builtin/more/names.id's
    init_resv_names splits this string into at startup.
    """
    names = sorted(idc.RUNTIME_HELPERS)
    block = f'{RESV_BEGIN}string resv_names_src = "{" ".join(names)}";\n{RESV_END}'

    with open(RESV_CONF) as f:
        text = f.read()
    if RESV_BEGIN in text:
        pre = text[:text.index(RESV_BEGIN)]
        post = text[text.index(RESV_END) + len(RESV_END):]
        text = pre + block + post
    else:
        sep = "" if text.endswith("\n") or text == "" else "\n"
        text = text + sep + block
    with open(RESV_CONF, "w") as f:
        f.write(text)
    print(f"wrote {RESV_CONF} ({len(names)} reserved names)")


if __name__ == "__main__":
    main()
