#!/usr/bin/env bash
# mkfont.sh -- regenerate the kernel's console font from a PSF font.
#
#   tools/mkfont.sh [FONT.psf[.gz]]
#
# With no argument it looks in the Nix store for lat0-16, lat2-16 or
# Lat2-Terminus16, as the kbd package installs them. tools/mkfont (in `id`)
# turns the font into the block of kernel/prog/conf.id that starts
# "// GENERATED by tools/mkfont", and into kernel/prog/sys/gfx/font/rom/all.id.
# This finds the font and unpacks it -- a console font ships gzipped and `id`
# has no gzip reader -- builds and runs the program, and puts both outputs in
# place. The block runs up to the blank line that ends it; the rest of conf.id
# is hand-written and is left as it is.
#
# Output is checked in, so a kernel build needs neither this script nor a font.
set -u
ROOT=$(cd "$(dirname "$0")/.." && pwd)
PROG=$ROOT/../kernel/prog
CONF=$PROG/conf.id
ALL=$PROG/sys/gfx/font/rom/all.id
MARK='// GENERATED by tools/mkfont'

src=${1:-}
if [ -z "$src" ]; then
    for pat in lat0-16.psfu.gz lat2-16.psfu.gz Lat2-Terminus16.psfu.gz; do
        for hit in /nix/store/*/share/consolefonts/$pat; do
            [ -e "$hit" ] && { src=$hit; break 2; }
        done
    done
fi
[ -n "$src" ] || { echo "mkfont.sh: no 8x16 PSF font found; pass one as an argument" >&2; exit 1; }

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

case "$src" in
    *.gz) gzip -dc "$src" > "$TMP/font.psf" ;;
    *)    cat "$src" > "$TMP/font.psf" ;;
esac || { echo "mkfont.sh: cannot read $src" >&2; exit 1; }

grep -q "^$MARK" "$CONF" || { echo "mkfont.sh: no '$MARK' block in $CONF" >&2; exit 1; }

env -u IDC_NO_STD "$ROOT/bin/idc" "$ROOT/tools/mkfont" --allow-untested -o "$TMP/mkfont" >&2 \
    || { echo "mkfont.sh: failed to build tools/mkfont" >&2; exit 1; }
name=$(basename "$src")
"$TMP/mkfont" "$TMP/font.psf" "$name" conf > "$TMP/block" || exit 1
"$TMP/mkfont" "$TMP/font.psf" "$name" all > "$TMP/all" || exit 1

awk -v mark="$MARK" -v block="$TMP/block" '
    skip && $0 == "" { skip = 0 }
    !done && index($0, mark) == 1 { while ((getline l < block) > 0) print l; skip = 1; done = 1 }
    !skip { print }
' "$CONF" > "$TMP/conf" && cat "$TMP/conf" > "$CONF" && cat "$TMP/all" > "$ALL" \
    || { echo "mkfont.sh: could not rewrite $CONF and $ALL" >&2; exit 1; }
echo "mkfont.sh: wrote the font block of $CONF and $ALL from $name"
