#!/usr/bin/env bash
# mkkeymap.sh -- regenerate the keymap block of kernel/prog/conf.id.
#
#   tools/mkkeymap.sh
#
# tools/mkkeymap (in `id`) prints the block: scancode set 1 to ASCII, unshifted
# and shifted. This builds and runs it and puts its output in place of the
# block already in conf.id, from the first line starting
# "// GENERATED by tools/mkkeymap" up to the blank line that ends the block.
# The rest of conf.id is hand-written and is left as it is.
set -u
ROOT=$(cd "$(dirname "$0")/.." && pwd)
CONF=$ROOT/../kernel/prog/conf.id
MARK='// GENERATED by tools/mkkeymap'

TMP=$(mktemp -d)
trap 'rm -rf "$TMP"' EXIT

grep -q "^$MARK" "$CONF" || { echo "mkkeymap.sh: no '$MARK' block in $CONF" >&2; exit 1; }

env -u IDC_NO_STD "$ROOT/bin/idc" "$ROOT/tools/mkkeymap" -o "$TMP/mkkeymap" >&2 \
    || { echo "mkkeymap.sh: failed to build tools/mkkeymap" >&2; exit 1; }
"$TMP/mkkeymap" > "$TMP/block" || { cat "$TMP/block" >&2; exit 1; }

awk -v mark="$MARK" -v block="$TMP/block" '
    skip && $0 == "" { skip = 0 }
    !done && index($0, mark) == 1 { while ((getline l < block) > 0) print l; skip = 1; done = 1 }
    !skip { print }
' "$CONF" > "$TMP/conf" && cat "$TMP/conf" > "$CONF" \
    || { echo "mkkeymap.sh: could not rewrite $CONF" >&2; exit 1; }
echo "mkkeymap.sh: wrote the keymap block of $CONF (128 entries each)"
